#include <bits/stdc++.h>
using namespace std;

// weak ordering cannot be generated by default, and the logic must be implemented

struct p {
    int a, b;
    std::weak_ordering operator <=> (p& other) {
        if (b < other.b) return std::weak_ordering::less;
        if (b > other.b) return std::weak_ordering::greater;

        return std::weak_ordering::equivalent;

    }
};

int main() {
    p Kai{5, 10};
    p Kai2{10, 10};

    vector<p>kais{Kai2, Kai};
    std::sort(kais.begin(), kais.end());
    for (auto x : kais) {
        cout << x.a << '\n';
    }

}